package com.stanzaliving.laundry.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.stanzaliving.laundry.enums.common.BooleanEnum;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import javax.persistence.Id;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@DynamoDBDocument
public class AbstractDynamoEntity {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private BooleanEnum entityStatus = BooleanEnum.TRUE;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

    @DynamoDBAttribute
    private String createdBy;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;

    @DynamoDBAttribute
    private String updatedBy;

}
